name: opengles-sample
version: "1.0"
architectures: [ all ]
summary: OpenGL ES samples (X11)
description: Simple OpenGL ES sample
confinement: devmode
type: app

apps:
 es2-tringle:
   command: bin/es2-tringle.wrapper
   plugs: [home, opengl, x11, unity7]
 es2-gears:
   command: bin/es2-gears.wrapper
   plugs: [home, opengl, x11, unity7]

parts:
 opengles-sample:
  plugin: make
  build-packages:
    - libx11-dev
    - libegl1-mesa
    - libgles2-mesa-dev
  stage-packages:
    - libegl1-mesa
    - libgles1-mesa
    - libgles2-mesa
    - libx11-dev
  source: src
 wrapper-copy:
  plugin: copy
  files:
   es2-tringle.wrapper: bin/es2-tringle.wrapper
   es2-gears.wrapper: bin/es2-gears.wrapper
